### Tensor Basics

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.5.0


In [ ]:
import os 

In [ ]:
#Initializations of tensors
x=tf.constant(4, shape=(1,1), dtype=tf.float32)

x =tf.constant([[1,2,3],[4,5,6]])

x=tf.ones((3,3))
x=tf.eye(3)

x=tf.random.normal((3,4), mean=0, stddev=1)
x=tf.random.uniform((3,4), minval=0, maxval=1)

x=tf.range(start=1, limit=10, delta=2 #step 
           )
x =tf.cast(x, dtype=tf.float64)
print(x)


tf.Tensor([1. 3. 5. 7. 9.], shape=(5,), dtype=float64)


In [ ]:
#Mathematical operations
x=tf.constant([1,2,3])
y=tf.constant([9,8,7])

#z=tf.add(x,y)
#z = x-y
#z= tf.divide(x,y)
z=tf.tensordot(x,y,axes=0)
z=tf.reduce_sum(x*y, axis=0)

z = x**2
#print(z)


tf.Tensor([1 4 9], shape=(3,), dtype=int32)


In [ ]:
x=tf.random.normal((2,3))
y=tf.random.normal((3,4))

#z=tf.matmul(x,y)
z = x @ y
print(z)

tf.Tensor(
[[ 0.44158053 -0.4297642   0.07948671  1.099791  ]
 [ 1.8887582  -0.0706126   0.80091405 -2.1331682 ]], shape=(2, 4), dtype=float32)


In [ ]:
#Indexing

x=tf.constant([0,1,1,2,3,1,2,3])
print(x[:])
print(x[1:])
print(x[1:3]) # it does not include the third element 
print(x[::2])
print(x[::-1])

tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)
tf.Tensor([1 1 2 3 1 2 3], shape=(7,), dtype=int32)
tf.Tensor([1 1], shape=(2,), dtype=int32)
tf.Tensor([0 1 3 2], shape=(4,), dtype=int32)
tf.Tensor([3 2 1 3 2 1 1 0], shape=(8,), dtype=int32)


In [ ]:
indices=tf.constant([0,3])
x_ind=tf.gather(x, indices)
print(x_ind)

tf.Tensor([0 2], shape=(2,), dtype=int32)


In [ ]:
x=tf.constant([[1,2],
               [3,4],
               [5,6]])
print(x[0,:])
print(x[0:2,:])

tf.Tensor([1 2], shape=(2,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [ ]:
#Reshaping a vector
x =tf.range(9)
x=tf.reshape(x, (3,3))
print(x)
y=tf.transpose(x, perm=[1,0])
print(y)


tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)


###  Neural Networks with Sequential and Functional API

In [ ]:
import tensorflow as tf
from tensorflow import keras

from tensorflow.keras import layers
from tensorflow.keras.datasets import mnist

# Loading mnist dataset

(x_train, y_train),(x_test,y_test)= mnist.load_data()
print(x_train.shape)
print(y_test.shape)


(60000, 28, 28)
(10000,)


In [ ]:
28*28

784

In [ ]:
x_train=x_train.reshape(-1,784).astype("float32") / 255.0
x_test=x_test.reshape(-1,28*28).astype("float32") / 255.0

In [ ]:
#Sequential API (convenient, not flexible)
model =keras.Sequential([
                         keras.Input(shape=(28*28)),
                         layers.Dense(512,activation="relu"),
                         layers.Dense(256, activation="relu"),
                         layers.Dense(10,activation="softmax")
])


model.compile(loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              optimizer= keras.optimizers.Adam(lr=0.001),
              metrics=["accuracy"])

model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 512)               401920    
_________________________________________________________________
dense_4 (Dense)              (None, 256)               131328    
_________________________________________________________________
dense_5 (Dense)              (None, 10)                2570      
Total params: 535,818
Trainable params: 535,818
Non-trainable params: 0
_________________________________________________________________


/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py:375: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  "The `lr` argument is deprecated, use `learning_rate` instead.")


In [ ]:
model1 =keras.Sequential()
model1.add(keras.Input(28*28))
model1.add(layers.Dense(512, activation="relu"))
model1.add(layers.Dense(256, activation="relu"))
model1.add(layers.Dense(10, activation="softmax"))

model1.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_6 (Dense)              (None, 512)               401920    
_________________________________________________________________
dense_7 (Dense)              (None, 256)               131328    
_________________________________________________________________
dense_8 (Dense)              (None, 10)                2570      
Total params: 535,818
Trainable params: 535,818
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.fit(x_train, y_train, batch_size=32,epochs=5, verbose=2)

Epoch 1/5


/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/backend.py:4930: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a sigmoid or softmax activation and thus does not represent logits. Was this intended?"
  '"`sparse_categorical_crossentropy` received `from_logits=True`, but '


1875/1875 - 7s - loss: 0.1881 - accuracy: 0.9428
Epoch 2/5
1875/1875 - 7s - loss: 0.0783 - accuracy: 0.9754
Epoch 3/5
1875/1875 - 7s - loss: 0.0547 - accuracy: 0.9829
Epoch 4/5
1875/1875 - 7s - loss: 0.0415 - accuracy: 0.9865
Epoch 5/5
1875/1875 - 7s - loss: 0.0321 - accuracy: 0.9895


In [ ]:
model.evaluate(x_test, y_test, batch_size=32, verbose=2)

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/backend.py:4930: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a sigmoid or softmax activation and thus does not represent logits. Was this intended?"
  '"`sparse_categorical_crossentropy` received `from_logits=True`, but '


313/313 - 1s - loss: 0.0765 - accuracy: 0.9780


[0.07646749913692474, 0.9779999852180481]

In [ ]:
# Functional API 

inputs= keras.Input(shape=(784))
x= layers.Dense(512, activation="relu", name="layer_1")(inputs)
x= layers.Dense(256, activation="relu", name="layer_2")(x)
outputs =layers.Dense(10, activation="softmax")(x)

model=keras.Model(inputs=inputs, outputs=outputs)

model.compile(loss=keras.losses.SparseCategoricalCrossentropy(from_logits=False),
              optimizer= keras.optimizers.Adam(lr=0.001),
              metrics=["accuracy"])

model.summary()

model.fit(x_train, y_train, batch_size=32,epochs=5, verbose=2)

model.evaluate(x_test, y_test, batch_size=32, verbose=2)

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py:375: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  "The `lr` argument is deprecated, use `learning_rate` instead.")


Model: "model_9"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_12 (InputLayer)        [(None, 784)]             0         
_________________________________________________________________
layer_1 (Dense)              (None, 512)               401920    
_________________________________________________________________
layer_2 (Dense)              (None, 256)               131328    
_________________________________________________________________
dense_22 (Dense)             (None, 10)                2570      
Total params: 535,818
Trainable params: 535,818
Non-trainable params: 0
_________________________________________________________________
Epoch 1/5
1875/1875 - 7s - loss: 0.1857 - accuracy: 0.9435
Epoch 2/5
1875/1875 - 7s - loss: 0.0788 - accuracy: 0.9760
Epoch 3/5
1875/1875 - 7s - loss: 0.0553 - accuracy: 0.9823
Epoch 4/5
1875/1875 - 7s - loss: 0.0418 - accuracy: 0.9867
Epoch 5/5
1875/

[0.0790274441242218, 0.9787999987602234]

In [ ]:
# Extracting Specific layer features
model =keras.Model(
    inputs=model.inputs,
    outputs= [model.output for layer in model.layers]
)

features = model.predict(x_train)
for feature in features:
  print(feature.shape)

(60000, 256)
(60000, 256)
(60000, 256)


In [ ]:
model =keras.Model(
    inputs=model.inputs,
    outputs= [model.get_layer('layer_2').output]
)

feature = model.predict(x_train)
print(feature.shape)

(60000, 256)


### Convolutional Neural Networks with Sequential and Functional API

In [ ]:
import tensorflow as tf
from tensorflow import keras 
from tensorflow.keras import layers
from tensorflow.keras.datasets import cifar10 

In [ ]:
#https://karpathy.github.io/2011/04/27/manually-classifying-cifar10/

In [ ]:
(x_train, y_train),(x_test, y_test)= cifar10.load_data()

x_train = x_train.astype("float32") / 255.0
x_test = x_test.astype("float32") / 255.0


170500096/170498071 [==============================] - 2s 0us/step


In [ ]:
print(x_train.shape)
print(x_test.shape)

print(y_train.shape)
print(y_test.shape)

(50000, 32, 32, 3)
(10000, 32, 32, 3)
(50000, 1)
(10000, 1)


In [ ]:
model=keras.Sequential([
                        keras.Input(shape=(32,32,3)),
                        layers.Conv2D(32, (3,3), padding="valid",activation="relu"),
                        layers.MaxPooling2D(pool_size=(2,2)),
                        layers.Conv2D(64,3, activation="relu"),
                        layers.MaxPool2D(),
                        layers.Conv2D(128, 3, activation="relu"),
                        layers.Flatten(),
                        layers.Dense(64, activation="relu"),
                        layers.Dense(10)
])

print(model.summary())

# Total number parameters: 225,034, very very small network, we dnt expect it to perform well 
# It is just to illustrate how to build CNNs 
# AlexNet : First CNN has about 660K units, 61M parameters, and over 600M connections. 
# Just to see how much our model is small 

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 30, 30, 32)        896       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 15, 15, 32)        0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 13, 13, 64)        18496     
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 6, 6, 64)          0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 4, 4, 128)         73856     
_________________________________________________________________
flatten (Flatten)            (None, 2048)              0         
_________________________________________________________________
dense (Dense)                (None, 64)                1

In [ ]:
model.compile(loss =keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              optimizer =keras.optimizers.Adam(lr=3e-4),
              metrics=["accuracy"])

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py:375: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  "The `lr` argument is deprecated, use `learning_rate` instead.")


In [ ]:
model.fit(x_train, y_train,batch_size=64 ,epochs= 20, verbose=2)


Epoch 1/20
782/782 - 54s - loss: 1.6569 - accuracy: 0.3988
Epoch 2/20
782/782 - 54s - loss: 1.3161 - accuracy: 0.5293
Epoch 3/20
782/782 - 54s - loss: 1.1956 - accuracy: 0.5785
Epoch 4/20
782/782 - 54s - loss: 1.0884 - accuracy: 0.6174
Epoch 5/20
782/782 - 54s - loss: 1.0134 - accuracy: 0.6467
Epoch 6/20
782/782 - 54s - loss: 0.9522 - accuracy: 0.6683
Epoch 7/20
782/782 - 54s - loss: 0.9010 - accuracy: 0.6867
Epoch 8/20
782/782 - 53s - loss: 0.8557 - accuracy: 0.7042
Epoch 9/20
782/782 - 54s - loss: 0.8172 - accuracy: 0.7185
Epoch 10/20
782/782 - 54s - loss: 0.7827 - accuracy: 0.7301
Epoch 11/20
782/782 - 53s - loss: 0.7546 - accuracy: 0.7391
Epoch 12/20
782/782 - 54s - loss: 0.7155 - accuracy: 0.7514
Epoch 13/20
782/782 - 54s - loss: 0.6891 - accuracy: 0.7618
Epoch 14/20
782/782 - 54s - loss: 0.6615 - accuracy: 0.7713
Epoch 15/20
782/782 - 54s - loss: 0.6344 - accuracy: 0.7796
Epoch 16/20
782/782 - 53s - loss: 0.6084 - accuracy: 0.7900
Epoch 17/20
782/782 - 53s - loss: 0.5877 - accura

In [ ]:
model.evaluate(x_test, y_test, batch_size=64, verbose=2)

157/157 - 3s - loss: 0.8322 - accuracy: 0.7316


[0.8321848511695862, 0.7315999865531921]

In [ ]:
# Functional API: 

def my_Model(): 
  inputs= keras.Input(shape=(32,32,3))
  x=layers.Conv2D(32,3)(inputs)
  x=layers.BatchNormalization()(x)
  x=keras.activations.relu(x)
  x=layers.MaxPooling2D()(x)
  x=layers.Conv2D(64,5, padding="same")(x)
  x=layers.BatchNormalization()(x)
  x=keras.activations.relu(x)
  x=layers.Conv2D(128,3)(x)
  x=layers.BatchNormalization()(x)
  x=keras.activations.relu(x)
  x=layers.Flatten()(x)
  x=layers.Dense(64, activation="relu")(x)
  outputs=layers.Dense(10)(x)
  model= keras.Model(inputs=inputs,
                     outputs=outputs)
  return model



In [ ]:
model = my_Model()
model.compile(loss =keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              optimizer =keras.optimizers.Adam(lr=3e-4),
              metrics=["accuracy"])

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py:375: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  "The `lr` argument is deprecated, use `learning_rate` instead.")


In [ ]:
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 32, 32, 3)]       0         
_________________________________________________________________
conv2d (Conv2D)              (None, 30, 30, 32)        896       
_________________________________________________________________
batch_normalization (BatchNo (None, 30, 30, 32)        128       
_________________________________________________________________
tf.nn.relu (TFOpLambda)      (None, 30, 30, 32)        0         
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 15, 15, 32)        0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 15, 15, 64)        51264     
_________________________________________________________________
batch_normalization_1 (Batch (None, 15, 15, 64)        256   

In [ ]:
model.fit(x_train, y_train,batch_size=64 ,epochs= 10, verbose=2)

Epoch 1/10


KeyboardInterrupt: ignored

In [ ]:
model.evaluate(x_test, y_test, verbose=2)

In [ ]:
#Adding Regularization with L2 and Dropout

from tensorflow.keras import regularizers

def my_Model(): 
  inputs= keras.Input(shape=(32,32,3))
  x=layers.Conv2D(32,3, 
                  padding="same", 
                  kernel_regularizer=regularizers.l2(0.02))(inputs)
  x=layers.BatchNormalization()(x)
  x=keras.activations.relu(x)
  x=layers.MaxPooling2D()(x)
  x=layers.Conv2D(64,5,
                  padding="same",
                  kernel_regularizer=regularizers.l2(0.01))(x)
  x=layers.BatchNormalization()(x)
  x=keras.activations.relu(x)
  x=layers.Conv2D(128,3, 
                  padding="same", 
                  kernel_regularizer=regularizers.l2(0.01))(x)
  x=layers.BatchNormalization()(x)
  x=keras.activations.relu(x)
  x=layers.Flatten()(x)
  x=layers.Dense(64, activation="relu",
                 kernel_regularizer=regularizers.l2(0.01))(x)
  x=layers.Dropout(0.5)(x)
  outputs=layers.Dense(10)(x)
  model= keras.Model(inputs=inputs,
                     outputs=outputs)
  return model



In [ ]:
model = my_Model()
model.compile(loss =keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              optimizer =keras.optimizers.Adam(lr=3e-4),
              metrics=["accuracy"])

print(model.summary())

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 32, 32, 3)]       0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 32, 32, 32)        896       
_________________________________________________________________
batch_normalization (BatchNo (None, 32, 32, 32)        128       
_________________________________________________________________
tf.nn.relu (TFOpLambda)      (None, 32, 32, 32)        0         
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 16, 16, 32)        0         
_________________________________________________________________
conv2d_4 (Conv2D)            (None, 16, 16, 64)        51264     
_________________________________________________________________
batch_normalization_1 (Batch (None, 16, 16, 64)        256   

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py:375: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  "The `lr` argument is deprecated, use `learning_rate` instead.")


In [ ]:
model.fit(x_train, y_train,batch_size=64 ,epochs= 150, verbose=2)
model.evaluate(x_test, y_test, verbose=2)

### RNNs, GRUs, LSTMs and Bidirectionality

In [ ]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.datasets import mnist

In [ ]:
(x_train, y_train),(x_test, y_test)= mnist.load_data()

11493376/11490434 [==============================] - 0s 0us/step


In [ ]:
x_train = x_train.astype('float32') / 255.0
x_test = x_test.astype('float32') / 255.0

In [ ]:
model =keras.Sequential()
model.add(keras.Input(shape=(None, 28)))
model.add(layers.SimpleRNN(512, return_sequences=True, activation="relu"))
model.add(layers.SimpleRNN(512, activation="relu"))
model.add(layers.Dense(10))

print(model.summary())

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn_2 (SimpleRNN)     (None, None, 512)         276992    
_________________________________________________________________
simple_rnn_3 (SimpleRNN)     (None, 512)               524800    
_________________________________________________________________
dense_4 (Dense)              (None, 10)                5130      
Total params: 806,922
Trainable params: 806,922
Non-trainable params: 0
_________________________________________________________________
None


In [ ]:
model.compile(loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              optimizer=keras.optimizers.Adam(lr=0.001),
              metrics=["accuracy"]
              )

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py:375: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  "The `lr` argument is deprecated, use `learning_rate` instead.")


In [ ]:
model.fit(x_train, y_train, epochs=20 ,batch_size=64 ,verbose=2)
model.evaluate(x_test, y_test, verbose=2)

Epoch 1/20
938/938 - 274s - loss: 0.2967 - accuracy: 0.9091
Epoch 2/20
938/938 - 276s - loss: 0.1388 - accuracy: 0.9625
Epoch 3/20
938/938 - 280s - loss: 0.1157 - accuracy: 0.9689
Epoch 4/20


KeyboardInterrupt: ignored

In [ ]:
#GRU
model =keras.Sequential()
model.add(keras.Input(shape=(None, 28)))
model.add(layers.GRU(512, return_sequences=True, activation="relu"))
model.add(layers.GRU(256, activation="relu"))
model.add(layers.Dense(10))

print(model.summary())

model.compile(loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              optimizer=keras.optimizers.Adam(lr=0.001),
              metrics=["accuracy"]
              )

model.fit(x_train, y_train, epochs=20 ,batch_size=64 ,verbose=2)
model.evaluate(x_test, y_test, verbose=2)

In [ ]:
#LSTM
model =keras.Sequential()
model.add(keras.Input(shape=(None, 28)))
model.add(layers.LSTM(512, return_sequences=True, activation="relu"))
model.add(layers.LSTM(256, activation="relu"))
model.add(layers.Dense(10))

print(model.summary())



In [ ]:
model.compile(loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              optimizer=keras.optimizers.Adam(lr=0.001),
              metrics=["accuracy"]
              )

model.fit(x_train, y_train, epochs=20 ,batch_size=64 ,verbose=2)
model.evaluate(x_test, y_test, verbose=2)

In [ ]:
# Bidirectionl LSTM
model =keras.Sequential()
model.add(keras.Input(shape=(None, 28)))
model.add(layers.Bidirectional(layers.LSTM(512, return_sequences=True, activation="relu")))
model.add(layers.Bidirectional(layers.LSTM(256, activation="relu")))
model.add(layers.Dense(10))

print(model.summary())


In [ ]:
model.compile(loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              optimizer=keras.optimizers.Adam(lr=0.001),
              metrics=["accuracy"]
              )

model.fit(x_train, y_train, epochs=20 ,batch_size=64 ,verbose=2)
model.evaluate(x_test, y_test, verbose=2)